GET https://backend-still-butterfly-8494.fly.dev/api/persons
###
POST https://backend-still-butterfly-8494.fly.dev/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Test User", 
    "number": "39-23-6423122"
}

###
POST https://backend-still-butterfly-8494.fly.dev/api/persons HTTP/1.1
content-type: application/json

{ 
    "name": "Mary Poppendieck", 
    "number": "39-23-6423122"
}

###
POST https://backend-still-butterfly-8494.fly.dev/api/persons HTTP/1.1
content-type: application/json

{  
    "number": "39-23-6423122"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{  
    "name": "Mary Poppendieck"
}